### ISSUE TITLE
Our sso page on pull request url still appearing v1.0.3 version of classes.

### ISSUE THREAD

**Issue by r-plus** [CherryCoder91/github-sso-login-clicker#1]
Hi @CherryCoder91 

In my case, "Continue" button of sso page on pull request url is still using `btn-primary btn btn-block` classes that fit v1.0.3.
<img width="407" alt="スクリーンショット 2023-12-22 11 46 06" src="https://github.com/CherryCoder91/github-sso-login-clicker/assets/425216/0e8e3c30-2c2a-44ed-9fc4-0f97b0bcb997">

this is html of button.

```html
<button type="submit" data-view-component="true" class="btn-primary btn btn-block">    Continue
</button>
```

So would you support both classes type v1.0.3(`btn-primary btn btn-block`) and v1.0.5(`Button--primary Button`).

**Comment by CherryCoder91** [comment]
Hi @r-plus thank you for the information and using the extension!

I have just made the changes and published up a new version (with updated icons also) to the store. It should go live soon! 

Let me know if you have any further issues, thanks!

**Comment by r-plus** [comment]
@CherryCoder91 thanks for your quick work.
v1.0.6 is works well in my environment 👍
