### ISSUE TITLE
Why this extension restricting url `/sso` and `/pull` since v1.0.5?

### ISSUE THREAD

**Issue by r-plus** [CherryCoder91/github-sso-login-clicker#2]
Hi @CherryCoder91 again.

Why this extension restricting url `/sso` and `/pull` since v1.0.5?

I often see the sso login screen in `/issues`.

**Comment by CherryCoder91** [comment]
Hi @r-plus,

They were limited as a 'precautionary' check to avoid the button being clicked on non sso pages. Originally It was thought that there was only a dedicated sso page url. Given this is not the case I have now removed the check (in version 1.0.7) and the sso click through should work now on any github url.

Again, thank you for your feedback and hope this solves your issue!

**Comment by r-plus** [comment]
okey, thanks 👍 
works perfectly 🎉
